#define GL_APIENTRY __stdcall

#if defined(_WIN64)
typedef long long int GLsizeiptr;
typedef long long int GLintptr;
#else
typedef long int GLsizeiptr;
typedef long int GLintptr;
#endif

typedef unsigned int GLenum;
typedef unsigned int GLuint;
typedef char GLchar;
typedef float GLfloat;
typedef unsigned int GLbitfield;
typedef int GLint;
typedef unsigned char GLboolean;
typedef int GLsizei;
typedef unsigned char GLubyte;

void (GL_APIENTRY *glActiveTexture)(GLenum texture);
void (GL_APIENTRY *glAttachShader)(GLuint program, GLuint shader);
void (GL_APIENTRY *glBindAttribLocation)(GLuint program, GLuint index, const GLchar *name);
void (GL_APIENTRY *glBindBuffer)(GLenum target, GLuint buffer);
void (GL_APIENTRY *glBindFramebuffer)(GLenum target, GLuint framebuffer);
void (GL_APIENTRY *glBindRenderbuffer)(GLenum target, GLuint renderbuffer);
void (GL_APIENTRY *glBindTexture)(GLenum target, GLuint texture);
void (GL_APIENTRY *glBlendColor)(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
void (GL_APIENTRY *glBlendEquation)(GLenum mode);
void (GL_APIENTRY *glBlendEquationSeparate)(GLenum modeRGB, GLenum modeAlpha);
void (GL_APIENTRY *glBlendFunc)(GLenum sfactor, GLenum dfactor);
void (GL_APIENTRY *glBlendFuncSeparate)(GLenum sfactorRGB, GLenum dfactorRGB, GLenum sfactorAlpha, GLenum dfactorAlpha);
void (GL_APIENTRY *glBufferData)(GLenum target, GLsizeiptr size, const void *data, GLenum usage);
void (GL_APIENTRY *glBufferSubData)(GLenum target, GLintptr offset, GLsizeiptr size, const void *data);
GLenum (GL_APIENTRY *glCheckFramebufferStatus)(GLenum target);
void (GL_APIENTRY *glClear)(GLbitfield mask);
void (GL_APIENTRY *glClearColor)(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
void (GL_APIENTRY *glClearDepthf)(GLfloat d);
void (GL_APIENTRY *glClearStencil)(GLint s);
void (GL_APIENTRY *glColorMask)(GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha);
void (GL_APIENTRY *glCompileShader)(GLuint shader);
void (GL_APIENTRY *glCompressedTexImage2D)(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const void *data);
void (GL_APIENTRY *glCompressedTexSubImage2D)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const void *data);
void (GL_APIENTRY *glCopyTexImage2D)(GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border);
void (GL_APIENTRY *glCopyTexSubImage2D)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height);
GLuint (GL_APIENTRY *glCreateProgram)(void);
GLuint (GL_APIENTRY *glCreateShader)(GLenum type);
void (GL_APIENTRY *glCullFace)(GLenum mode);
void (GL_APIENTRY *glDeleteBuffers)(GLsizei n, const GLuint *buffers);
void (GL_APIENTRY *glDeleteFramebuffers)(GLsizei n, const GLuint *framebuffers);
void (GL_APIENTRY *glDeleteProgram)(GLuint program);
void (GL_APIENTRY *glDeleteRenderbuffers)(GLsizei n, const GLuint *renderbuffers);
void (GL_APIENTRY *glDeleteShader)(GLuint shader);
void (GL_APIENTRY *glDeleteTextures)(GLsizei n, const GLuint *textures);
void (GL_APIENTRY *glDepthFunc)(GLenum func);
void (GL_APIENTRY *glDepthMask)(GLboolean flag);
void (GL_APIENTRY *glDepthRangef)(GLfloat n, GLfloat f);
void (GL_APIENTRY *glDetachShader)(GLuint program, GLuint shader);
void (GL_APIENTRY *glDisable)(GLenum cap);
void (GL_APIENTRY *glDisableVertexAttribArray)(GLuint index);
void (GL_APIENTRY *glDrawArrays)(GLenum mode, GLint first, GLsizei count);
void (GL_APIENTRY *glDrawElements)(GLenum mode, GLsizei count, GLenum type, const void *indices);
void (GL_APIENTRY *glEnable)(GLenum cap);
void (GL_APIENTRY *glEnableVertexAttribArray)(GLuint index);
void (GL_APIENTRY *glFinish)(void);
void (GL_APIENTRY *glFlush)(void);
void (GL_APIENTRY *glFramebufferRenderbuffer)(GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer);
void (GL_APIENTRY *glFramebufferTexture2D)(GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level);
void (GL_APIENTRY *glFrontFace)(GLenum mode);
void (GL_APIENTRY *glGenBuffers)(GLsizei n, GLuint *buffers);
void (GL_APIENTRY *glGenerateMipmap)(GLenum target);
void (GL_APIENTRY *glGenFramebuffers)(GLsizei n, GLuint *framebuffers);
void (GL_APIENTRY *glGenRenderbuffers)(GLsizei n, GLuint *renderbuffers);
void (GL_APIENTRY *glGenTextures)(GLsizei n, GLuint *textures);
void (GL_APIENTRY *glGetActiveAttrib)(GLuint program, GLuint index, GLsizei bufSize, GLsizei *length, GLint *size, GLenum *type, GLchar *name);
void (GL_APIENTRY *glGetActiveUniform)(GLuint program, GLuint index, GLsizei bufSize, GLsizei *length, GLint *size, GLenum *type, GLchar *name);
void (GL_APIENTRY *glGetAttachedShaders)(GLuint program, GLsizei maxCount, GLsizei *count, GLuint *shaders);
GLint (GL_APIENTRY *glGetAttribLocation)(GLuint program, const GLchar *name);
void (GL_APIENTRY *glGetBooleanv)(GLenum pname, GLboolean *data);
void (GL_APIENTRY *glGetBufferParameteriv)(GLenum target, GLenum pname, GLint *params);
GLenum (GL_APIENTRY *glGetError)(void);
void (GL_APIENTRY *glGetFloatv)(GLenum pname, GLfloat *data);
void (GL_APIENTRY *glGetFramebufferAttachmentParameteriv)(GLenum target, GLenum attachment, GLenum pname, GLint *params);
void (GL_APIENTRY *glGetIntegerv)(GLenum pname, GLint *data);
void (GL_APIENTRY *glGetProgramiv)(GLuint program, GLenum pname, GLint *params);
void (GL_APIENTRY *glGetProgramInfoLog)(GLuint program, GLsizei bufSize, GLsizei *length, GLchar *infoLog);
void (GL_APIENTRY *glGetRenderbufferParameteriv)(GLenum target, GLenum pname, GLint *params);
void (GL_APIENTRY *glGetShaderiv)(GLuint shader, GLenum pname, GLint *params);
void (GL_APIENTRY *glGetShaderInfoLog)(GLuint shader, GLsizei bufSize, GLsizei *length, GLchar *infoLog);
void (GL_APIENTRY *glGetShaderPrecisionFormat)(GLenum shadertype, GLenum precisiontype, GLint *range, GLint *precision);
void (GL_APIENTRY *glGetShaderSource)(GLuint shader, GLsizei bufSize, GLsizei *length, GLchar *source);
const GLubyte *(GL_APIENTRY *glGetString)(GLenum name);
void (GL_APIENTRY *glGetTexParameterfv)(GLenum target, GLenum pname, GLfloat *params);
void (GL_APIENTRY *glGetTexParameteriv)(GLenum target, GLenum pname, GLint *params);
void (GL_APIENTRY *glGetUniformfv)(GLuint program, GLint location, GLfloat *params);
void (GL_APIENTRY *glGetUniformiv)(GLuint program, GLint location, GLint *params);
GLint (GL_APIENTRY *glGetUniformLocation)(GLuint program, const GLchar *name);
void (GL_APIENTRY *glGetVertexAttribfv)(GLuint index, GLenum pname, GLfloat *params);
void (GL_APIENTRY *glGetVertexAttribiv)(GLuint index, GLenum pname, GLint *params);
void (GL_APIENTRY *glGetVertexAttribPointerv)(GLuint index, GLenum pname, void **pointer);
void (GL_APIENTRY *glHint)(GLenum target, GLenum mode);
GLboolean (GL_APIENTRY *glIsBuffer)(GLuint buffer);
GLboolean (GL_APIENTRY *glIsEnabled)(GLenum cap);
GLboolean (GL_APIENTRY *glIsFramebuffer)(GLuint framebuffer);
GLboolean (GL_APIENTRY *glIsProgram)(GLuint program);
GLboolean (GL_APIENTRY *glIsRenderbuffer)(GLuint renderbuffer);
GLboolean (GL_APIENTRY *glIsShader)(GLuint shader);
GLboolean (GL_APIENTRY *glIsTexture)(GLuint texture);
void (GL_APIENTRY *glLineWidth)(GLfloat width);
void (GL_APIENTRY *glLinkProgram)(GLuint program);
void (GL_APIENTRY *glPixelStorei)(GLenum pname, GLint param);
void (GL_APIENTRY *glPolygonOffset)(GLfloat factor, GLfloat units);
void (GL_APIENTRY *glReadPixels)(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, void *pixels);
void (GL_APIENTRY *glReleaseShaderCompiler)(void);
void (GL_APIENTRY *glRenderbufferStorage)(GLenum target, GLenum internalformat, GLsizei width, GLsizei height);
void (GL_APIENTRY *glSampleCoverage)(GLfloat value, GLboolean invert);
void (GL_APIENTRY *glScissor)(GLint x, GLint y, GLsizei width, GLsizei height);
void (GL_APIENTRY *glShaderBinary)(GLsizei count, const GLuint *shaders, GLenum binaryFormat, const void *binary, GLsizei length);
void (GL_APIENTRY *glShaderSource)(GLuint shader, GLsizei count, const GLchar *const*string, const GLint *length);
void (GL_APIENTRY *glStencilFunc)(GLenum func, GLint ref, GLuint mask);
void (GL_APIENTRY *glStencilFuncSeparate)(GLenum face, GLenum func, GLint ref, GLuint mask);
void (GL_APIENTRY *glStencilMask)(GLuint mask);
void (GL_APIENTRY *glStencilMaskSeparate)(GLenum face, GLuint mask);
void (GL_APIENTRY *glStencilOp)(GLenum fail, GLenum zfail, GLenum zpass);
void (GL_APIENTRY *glStencilOpSeparate)(GLenum face, GLenum sfail, GLenum dpfail, GLenum dppass);
void (GL_APIENTRY *glTexImage2D)(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const void *pixels);
void (GL_APIENTRY *glTexParameterf)(GLenum target, GLenum pname, GLfloat param);
void (GL_APIENTRY *glTexParameterfv)(GLenum target, GLenum pname, const GLfloat *params);
void (GL_APIENTRY *glTexParameteri)(GLenum target, GLenum pname, GLint param);
void (GL_APIENTRY *glTexParameteriv)(GLenum target, GLenum pname, const GLint *params);
void (GL_APIENTRY *glTexSubImage2D)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const void *pixels);
void (GL_APIENTRY *glUniform1f)(GLint location, GLfloat v0);
void (GL_APIENTRY *glUniform1fv)(GLint location, GLsizei count, const GLfloat *value);
void (GL_APIENTRY *glUniform1i)(GLint location, GLint v0);
void (GL_APIENTRY *glUniform1iv)(GLint location, GLsizei count, const GLint *value);
void (GL_APIENTRY *glUniform2f)(GLint location, GLfloat v0, GLfloat v1);
void (GL_APIENTRY *glUniform2fv)(GLint location, GLsizei count, const GLfloat *value);
void (GL_APIENTRY *glUniform2i)(GLint location, GLint v0, GLint v1);
void (GL_APIENTRY *glUniform2iv)(GLint location, GLsizei count, const GLint *value);
void (GL_APIENTRY *glUniform3f)(GLint location, GLfloat v0, GLfloat v1, GLfloat v2);
void (GL_APIENTRY *glUniform3fv)(GLint location, GLsizei count, const GLfloat *value);
void (GL_APIENTRY *glUniform3i)(GLint location, GLint v0, GLint v1, GLint v2);
void (GL_APIENTRY *glUniform3iv)(GLint location, GLsizei count, const GLint *value);
void (GL_APIENTRY *glUniform4f)(GLint location, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3);
void (GL_APIENTRY *glUniform4fv)(GLint location, GLsizei count, const GLfloat *value);
void (GL_APIENTRY *glUniform4i)(GLint location, GLint v0, GLint v1, GLint v2, GLint v3);
void (GL_APIENTRY *glUniform4iv)(GLint location, GLsizei count, const GLint *value);
void (GL_APIENTRY *glUniformMatrix2fv)(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void (GL_APIENTRY *glUniformMatrix3fv)(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void (GL_APIENTRY *glUniformMatrix4fv)(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void (GL_APIENTRY *glUseProgram)(GLuint program);
void (GL_APIENTRY *glValidateProgram)(GLuint program);
void (GL_APIENTRY *glVertexAttrib1f)(GLuint index, GLfloat x);
void (GL_APIENTRY *glVertexAttrib1fv)(GLuint index, const GLfloat *v);
void (GL_APIENTRY *glVertexAttrib2f)(GLuint index, GLfloat x, GLfloat y);
void (GL_APIENTRY *glVertexAttrib2fv)(GLuint index, const GLfloat *v);
void (GL_APIENTRY *glVertexAttrib3f)(GLuint index, GLfloat x, GLfloat y, GLfloat z);
void (GL_APIENTRY *glVertexAttrib3fv)(GLuint index, const GLfloat *v);
void (GL_APIENTRY *glVertexAttrib4f)(GLuint index, GLfloat x, GLfloat y, GLfloat z, GLfloat w);
void (GL_APIENTRY *glVertexAttrib4fv)(GLuint index, const GLfloat *v);
void (GL_APIENTRY *glVertexAttribPointer)(GLuint index, GLint size, GLenum type, GLboolean normalized, GLsizei stride, const void *pointer);
void (GL_APIENTRY *glViewport)(GLint x, GLint y, GLsizei width, GLsizei height);

void gl_load(void *(*load)(const char *))
{
	glActiveTexture = load("glActiveTexture");
	glAttachShader = load("glAttachShader");
	glBindAttribLocation = load("glBindAttribLocation");
	glBindBuffer = load("glBindBuffer");
	glBindFramebuffer = load("glBindFramebuffer");
	glBindRenderbuffer = load("glBindRenderbuffer");
	glBindTexture = load("glBindTexture");
	glBlendColor = load("glBlendColor");
	glBlendEquation = load("glBlendEquation");
	glBlendEquationSeparate = load("glBlendEquationSeparate");
	glBlendFunc = load("glBlendFunc");
	glBlendFuncSeparate = load("glBlendFuncSeparate");
	glBufferData = load("glBufferData");
	glBufferSubData = load("glBufferSubData");
	glCheckFramebufferStatus = load("glCheckFramebufferStatus");
	glClear = load("glClear");
	glClearColor = load("glClearColor");
	glClearDepthf = load("glClearDepthf");
	glClearStencil = load("glClearStencil");
	glColorMask = load("glColorMask");
	glCompileShader = load("glCompileShader");
	glCompressedTexImage2D = load("glCompressedTexImage2D");
	glCompressedTexSubImage2D = load("glCompressedTexSubImage2D");
	glCopyTexImage2D = load("glCopyTexImage2D");
	glCopyTexSubImage2D = load("glCopyTexSubImage2D");
	glCreateProgram = load("glCreateProgram");
	glCreateShader = load("glCreateShader");
	glCullFace = load("glCullFace");
	glDeleteBuffers = load("glDeleteBuffers");
	glDeleteFramebuffers = load("glDeleteFramebuffers");
	glDeleteProgram = load("glDeleteProgram");
	glDeleteRenderbuffers = load("glDeleteRenderbuffers");
	glDeleteShader = load("glDeleteShader");
	glDeleteTextures = load("glDeleteTextures");
	glDepthFunc = load("glDepthFunc");
	glDepthMask = load("glDepthMask");
	glDepthRangef = load("glDepthRangef");
	glDetachShader = load("glDetachShader");
	glDisable = load("glDisable");
	glDisableVertexAttribArray = load("glDisableVertexAttribArray");
	glDrawArrays = load("glDrawArrays");
	glDrawElements = load("glDrawElements");
	glEnable = load("glEnable");
	glEnableVertexAttribArray = load("glEnableVertexAttribArray");
	glFinish = load("glFinish");
	glFlush = load("glFlush");
	glFramebufferRenderbuffer = load("glFramebufferRenderbuffer");
	glFramebufferTexture2D = load("glFramebufferTexture2D");
	glFrontFace = load("glFrontFace");
	glGenBuffers = load("glGenBuffers");
	glGenerateMipmap = load("glGenerateMipmap");
	glGenFramebuffers = load("glGenFramebuffers");
	glGenRenderbuffers = load("glGenRenderbuffers");
	glGenTextures = load("glGenTextures");
	glGetActiveAttrib = load("glGetActiveAttrib");
	glGetActiveUniform = load("glGetActiveUniform");
	glGetAttachedShaders = load("glGetAttachedShaders");
	glGetAttribLocation = load("glGetAttribLocation");
	glGetBooleanv = load("glGetBooleanv");
	glGetBufferParameteriv = load("glGetBufferParameteriv");
	glGetError = load("glGetError");
	glGetFloatv = load("glGetFloatv");
	glGetFramebufferAttachmentParameteriv = load("glGetFramebufferAttachmentParameteriv");
	glGetIntegerv = load("glGetIntegerv");
	glGetProgramiv = load("glGetProgramiv");
	glGetProgramInfoLog = load("glGetProgramInfoLog");
	glGetRenderbufferParameteriv = load("glGetRenderbufferParameteriv");
	glGetShaderiv = load("glGetShaderiv");
	glGetShaderInfoLog = load("glGetShaderInfoLog");
	glGetShaderPrecisionFormat = load("glGetShaderPrecisionFormat");
	glGetShaderSource = load("glGetShaderSource");
	glGetString = load("glGetString");
	glGetTexParameterfv = load("glGetTexParameterfv");
	glGetTexParameteriv = load("glGetTexParameteriv");
	glGetUniformfv = load("glGetUniformfv");
	glGetUniformiv = load("glGetUniformiv");
	glGetUniformLocation = load("glGetUniformLocation");
	glGetVertexAttribfv = load("glGetVertexAttribfv");
	glGetVertexAttribiv = load("glGetVertexAttribiv");
	glGetVertexAttribPointerv = load("glGetVertexAttribPointerv");
	glHint = load("glHint");
	glIsBuffer = load("glIsBuffer");
	glIsEnabled = load("glIsEnabled");
	glIsFramebuffer = load("glIsFramebuffer");
	glIsProgram = load("glIsProgram");
	glIsRenderbuffer = load("glIsRenderbuffer");
	glIsShader = load("glIsShader");
	glIsTexture = load("glIsTexture");
	glLineWidth = load("glLineWidth");
	glLinkProgram = load("glLinkProgram");
	glPixelStorei = load("glPixelStorei");
	glPolygonOffset = load("glPolygonOffset");
	glReadPixels = load("glReadPixels");
	glReleaseShaderCompiler = load("glReleaseShaderCompiler");
	glRenderbufferStorage = load("glRenderbufferStorage");
	glSampleCoverage = load("glSampleCoverage");
	glScissor = load("glScissor");
	glShaderBinary = load("glShaderBinary");
	glShaderSource = load("glShaderSource");
	glStencilFunc = load("glStencilFunc");
	glStencilFuncSeparate = load("glStencilFuncSeparate");
	glStencilMask = load("glStencilMask");
	glStencilMaskSeparate = load("glStencilMaskSeparate");
	glStencilOp = load("glStencilOp");
	glStencilOpSeparate = load("glStencilOpSeparate");
	glTexImage2D = load("glTexImage2D");
	glTexParameterf = load("glTexParameterf");
	glTexParameterfv = load("glTexParameterfv");
	glTexParameteri = load("glTexParameteri");
	glTexParameteriv = load("glTexParameteriv");
	glTexSubImage2D = load("glTexSubImage2D");
	glUniform1f = load("glUniform1f");
	glUniform1fv = load("glUniform1fv");
	glUniform1i = load("glUniform1i");
	glUniform1iv = load("glUniform1iv");
	glUniform2f = load("glUniform2f");
	glUniform2fv = load("glUniform2fv");
	glUniform2i = load("glUniform2i");
	glUniform2iv = load("glUniform2iv");
	glUniform3f = load("glUniform3f");
	glUniform3fv = load("glUniform3fv");
	glUniform3i = load("glUniform3i");
	glUniform3iv = load("glUniform3iv");
	glUniform4f = load("glUniform4f");
	glUniform4fv = load("glUniform4fv");
	glUniform4i = load("glUniform4i");
	glUniform4iv = load("glUniform4iv");
	glUniformMatrix2fv = load("glUniformMatrix2fv");
	glUniformMatrix3fv = load("glUniformMatrix3fv");
	glUniformMatrix4fv = load("glUniformMatrix4fv");
	glUseProgram = load("glUseProgram");
	glValidateProgram = load("glValidateProgram");
	glVertexAttrib1f = load("glVertexAttrib1f");
	glVertexAttrib1fv = load("glVertexAttrib1fv");
	glVertexAttrib2f = load("glVertexAttrib2f");
	glVertexAttrib2fv = load("glVertexAttrib2fv");
	glVertexAttrib3f = load("glVertexAttrib3f");
	glVertexAttrib3fv = load("glVertexAttrib3fv");
	glVertexAttrib4f = load("glVertexAttrib4f");
	glVertexAttrib4fv = load("glVertexAttrib4fv");
	glVertexAttribPointer = load("glVertexAttribPointer");
	glViewport = load("glViewport");
}
